name: Deploy Tomcat CI-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy to Control Node
        run: |
          scp -r . ansible@CONTROL_NODE_IP:/home/ansible/app

      - name: Run Ansible Playbook
        run: |
          ssh ansible@CONTROL_NODE_IP << 'EOF'
          cd /home/ansible/app
          ansible-playbook -i inventory.ini deploy.yml
          EOF
